#+TITLE: On Boarding Document
#+AUTHOR: VLEAD
#+DATE: [2017-05-04 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Things to Do before [2017-06-01 Thu]

  1. Work on both the parts - A & B - of [[http://pascal.iiit.ac.in/~itws2/docs/current-topics/lab-exam/instructions.html][final exam]].  On the first day of the
     internship you should show us that all your test cases run.
  2. Setup your machine with [[https://www.vagrantup.com/intro/getting-started/index.html][Vagrant]] for virtualization.
  3. Create an ubuntu 14.04 Virtual Machine using Vagrant.
  4. Install emacs 24.x.x, git in that machine.
  5. Read about [[https://martinfowler.com/articles/microservices.html][microservices]].

* Welcome

  Welcome to Virtual Labs - 2017 Summer Internship Program @ IIITH !!!

  We are delighted you are joining us as a new intern. This program has been
  developed for students to gain practical training and hands-on, real world
  experience that will help them meet their educational goals and prepare them
  for a professional career.  The VLEAD team is here to support your
  transition, so can call on any of us to assist you.

* Instructions to Interns
  1) An RFID card will be issued to you on Day 1 of the internship
   program by Ravi Kiran, Program Officer, Virtual Labs. This should
   be swiped everyday at B6-205, VLEAD Room (when you come in and
   leave) for logging attendance.

  2) An LDAP account will be created for you on a need basis.

  3) Please create a GitLab account (https://gitlab.com/) and share you account
     information with raghupathi@vlabs.ac.in.

  4) Your working hours for the internship period is from 9:00 A.M to 6:00P.M
     (Monday - Friday) .

  5) You are allowed to take only one leave in a month with prior notice to
     your mentor during the internship period.

  6) Wok logs to be committed at the end of every day.  Create a file
     =first-name.org= in the =work-logs= directory and fill in the details.
     Please use =sample.org= as a template.

  7) You have to get your work-log approved from your mentor on a weekly
     basis. You will also need to submit your approved work-log to
     ravi.kiran@vlabs.ac.in . Your stipend will be released against this
     submission only.

  8) All Friday afternoons will be reserved for a short presentation (5-10
     mins) by the interns on their project and progress.

  9) You will need to make a mid-internship presentation at the end of the 4th
     week of internship - week of 29th June to 6th July 2017.

  10) A final presentation (with links to relevant documents) will need to be
      made during the week of 13th July to 20th July 2017 against which the
      internship certificate will be issued.
