#+TITLE: worklog of Anirudh Reddy
#+AUTHOR: Anirudh Reddy
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
+ [2017-06-01 Thu] - Installed virtual box and setup up vagrant with ubuntu 14.04 .
   Revised some of the itws-2 course material and worked out some of the lab tasks and assignments.

+ [2017-06-02 Fri] - worked out some more assignments and lab tasks .Did some online problems and explored some new Jquery and DOM interactions.

** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
+ [2017-06-05 Mon] - read the documentation and ran the app which was on GitHub.Had some trouble while installing mysql and Flask in virtualbox(vagrant) and lost some time due to that.Had a meeting with the project manager and dicussed in detail about the app and the working and were given a few tasks to complete and draw the process diagram .

+ [2017-06-06 Tue] - We had a meeting with our project manager in the morning and were asked to install ALLOY analyzer which is a specification language which can used to check the model.Me and my project-mate set up a milestone for the coming friday.In the afternoon I spent reading the alloy tutorials and then tried the alloy analyzer.I added a work-flow chart of the engine-gaurd diagram through google.docs.

+ [2017-06-07 Wed] - Did some examples of models in Alloy analyzer. Tried to build the model of web app short course but was not able to implement/code in the alloy analyzer properly.Working on some more concepts and tutorials of alloy.

+ [2017+-06-08 Thu] - made a few example models in alloy and did some of the alloy tutorials.

+ [2017+-06-09 Fri] - made a static model of Webapp-short-course in Alloy and  implemented the operation AddUser and checked some cases with assertion.
** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]  

+ [2017+-06-12 Mon] - Completed the documentation of the Alloy model of web app short course

+ [2017+-06-13 Tue] - Edited and improved documentataion of the Alloy model of web app short course

+ [2017+-06-14 Wed] - Working on building session entity in the Alloy model created before for web app short course

+ [2017+-06-15 Thu] - Had a discussion with prof Venkatesh and Mr.Thirumal about where our work is added and Also made a static model including the session.

+ [2017+-06-16 Fri] - worked on the presentation.Had a discussion with Prof venkatesh and Akash about FIM and its vulnerabilities.Was asked to look at the papers of Ganesh on CORP and read about FIM.

** Week 4 [2017-06-19 Mon] till [2017-06-25 Sun]

+ [2017+-06-19 Mon] - worked on the Alloy model and included session entity to it and working on the dynamic model with session.

+ [2017+-06-20 Tue] - Added the login and logout and completed the alloy model of webapp short course with session and dynamic operations. Akash asked us to read about the vulnerabilities in FIM and some papers found on google.

+ [2017+-06-21 Wed] - Had a discussion with Prof Venkatesh and Mr.Thirumal and i was asked to comple the routing of the webapp short course. I explored all routings in Webapp short course and installed some of the required software for my mac.

+ [2017+-06-22 Thu] - Had a discussion with with Mr.Thirumal and sat with him to understand a few things about emacs like how to use magit and also looked at the =P= and =T= . Starting working on writing the routes for some more operations in webapp short course.Made a list of all the operations that could be added and started with writing the route for adding a role to a user. 

+ [2017+-06-23 Fri] - Added the login and logout operations to the documentation of the alloy model of webapp short course and improved the documentation adn added the session part to it and made a few changes to the images and added revised images.Mr Thirumal asked me to look at the elisp/incr-build file and study the functions in it and make a few changes so that the tangled out files go not only to the destination directory but each to a new respective directory in the destination dirtectory depending upon the initial destination of the file.
   
** Week 5 [2017-06-26 Mon] till [2017-07-2 Sun]
+ [2017+-06-27 Tue] - Had a talk with Prof Venkatesh and he checked my worklogs .He looked at the documentation of the    alloy model of webapp short course and asked me to increase the readabilty by explaining each and every line of the code and explain the diagrams which were included.I worked on improving the documentation for some time and worked on writing the routes for Add_Role(add a role) and Del_Role(delete a role).I have completed the guard and engine part of both the operations.Writing the tests for them is pending.

+  [2017+-06-28 Wed] - Changed the documentation of the alloy datamodel of webapp short course for more readability.Added explanation for each line of alloy code in the documentation and labelled the diagrams for better navigation.Also checked for any mistakes or typos in the documentation.Worked on writing the route for =show_sessions= .Completed the routing for guard and engine part of =show_sessions= operations.

+  [2017+-06-29 Thu] - Worked on writing the route for =set_name= and =set_email= operations.Completed the engine and guard routings for =set_name= (set the name of a user) and =set_email= (set the email of a user).Had a talk with Mr.Thirumal and he asked me to write the tests for the operations simultaneously while writing their engine and guard routes.So, I starting working on writing the tests for the =guard= part of =set_name= and =set_email=.Wrote 5 tests for each of the above operations and also the setup class.

+  [2017+-06-30 Fri] - Applied for leave.

** Week 5 [2017-07-3 Mon] till [2017-07-9 Sun]
+  [2017+-07-3 Mon] - Worked on writing the tests for add_role,del_role,set_name,set_email,show_sessions operations .Completed writing the tests for both engine and guard components of the above operations.wrote about 24 tests in total.
+  [2017+-07-4 Tue] - worked on debugging the tests and writing some more tests for the engine and guard of the operations.Had a talk with Mr.Thirumal and he helped me in doing incremental build and sorted a few issues in my laptop.After lunch, the entire day went in debugging the test cases.
+  [2017+-07-5 Wed] - Had a talk with Mr.Thirumal about where our project is headed to i.e, goal is to automate the process of building the application when specifications are given and to implement the actor model.Then I started degugging the code of the routes for engine and gaurd of the operations .Ran the tests for them.I was stuck with an error which I couldnt solve, so I sat down with Thirumal Sir and found the bug.Then I started degugging the remaining errors.More one error is left to debug 
+  [2017+-07-6 Thu] - Was degugging the gaurd route of add_role operation and was stuck with one error.Had some debugging to do in the gaurd part of del_role operation .Starting working on adding a new operation get_user_by_email(Which gets the user from the entity with the given email in the instruction).Completed the route for gaurd part of the get_user_by_email operation and also wrote 5 tests for it.Debugged the code according to the errors when i ran the tests. Finally completed the gaurd part of the get_user_by_email operation along with tests.
+  [2017+-07-7 Fri] - prepared a presentation file for the work i have done.started work on building the engine route of GetUser by email.Completed the engine route for Getuser by email and also wrote tests and ran them.Then started work on adding another route ie, Get_roles_of_user .Completed the guard route of get_roles_of_user and wrote tests and ran them 

** Week 6 [2017-07-10 Mon] till [2017-07-16 Sun]
+  [2017+-07-10 Mon] - Completed the engine and guard routes of Show_user_details .Wrote tests and ran them.Fixed the errors.Added more tests for the guard route.Fixed some errors and bugs in the add_role route.Test cases for add_role now pass without error.Fixed some typos and errors in the routes which were already built previously
+  [2017+-07-11 Tue] - Started working on writing the route for GetRoleSet.Completed the route for the guard of get_role_set_in_system and wrote tests and ran them.Fixed some errors after running the tests.Talked with Atreyee on how my work could be useful for her .Then i completed the engine route of the get_role_set_in_system operation.Wrote tests for it and ran them and fixed the errors generates after running those tests.
+  [2017+-07-12 Wed] - Added explanation to the routes and made them more readable.Had a talk with Mr.Thirumal about my work and he asked me to look at the rest API in the master branch and see how it works.He asked me to build an instruction creator which takes in an input and creats an instruction out of it and sends it to the guard or engine.
