#+TITLE: worklog of Anirudh Reddy
#+AUTHOR: Anirudh Reddy
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Installed virtual box and setup up vagrant with ubuntu 14.04 .
   Revised some of the itws-2 course material and worked out some of the lab tasks and assignments.
   + [2017-06-02 Fri] - worked out some more assignments and lab tasks .Did some online problems and explored some new Jquery and DOM interactions.

** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - read the documentation and ran the app which was on GitHub.Had some trouble while installing mysql and Flask in virtualbox(vagrant) and lost some time due to that.Had a meeting with the project manager and dicussed in detail about the app and the working and were given a few tasks to complete and draw the process diagram .
   + [2017-06-06 Tue] - We had a meeting with our project manager in the morning and were asked to install ALLOY analyzer which is a specification language which can used to check the model.Me and my project-mate set up a milestone for the coming friday.In the afternoon I spent reading the alloy tutorials and then tried the alloy analyzer.I added a work-flow chart of the engine-gaurd diagram through google.docs.
   + [2017-06-07 Wed] - Did some examples of models in Alloy analyzer. Tried to build the model of web app short course but was not able to implement/code in the alloy analyzer properly.Working on some more concepts and tutorials of alloy.
   + [2017+-06-08 Thu] - made a few example models in alloy and did some of the alloy tutorials.
   + [2017+-06-09 Fri] - made a static model of Webapp-short-course in Alloy and  implemented the operation AddUser and checked some cases with assertion.
** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]  
   + [2017+-06-12 Mon] - Completed the documentation of the Alloy model of web app short course
   + [2017+-06-13 Tue] - Edited and improved documentataion of the Alloy model of web app short course
   + [2017+-06-14 Wed] - Working on building session entity in the Alloy model created before for web app short course
   + [2017+-06-15 Thu] - Had a discussion with prof Venkatesh and Mr.Thirumal about where our work is added and Also made a static model including the session.
   + [2017+-06-16 Fri] - worked on the presentation.Had a discussion with Prof venkatesh and Akash about FIM and its vulnerabilities.Was asked to look at the papers of Ganesh on CORP and read about FIM.
** Week 3 [2017-06-19 Mon] till [2017-06-25 Sun]
   + [2017+-06-19 Mon] - worked on the Alloy model and included session entity to it and working on the dynamic model with session.
   + [2017+-06-20 Tue] - Added the login and logout and completed the alloy model of webapp short course with session and dynamic operations. Akash asked us to read about the vulnerabilities in FIM and some papers found on google.
   + [2017+-06-21 Wed] - Had a discussion with Prof Venkatesh and Mr.Thirumal and i was asked to comple the routing of the webapp short course. I explored all routings in Webapp short course and installed some of the required software for my mac.
