#+TITLE: Time sheet
#+AUTHOR: Kalpit Pokra
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

  

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Worked on setting up environments. Read the documentry
     regarding conversion to java script of flash to understand work.Then went through some experiments to understand
     how to work and tried to select lab and experiment as first task.
   + [2017-06-02] - Tried to Understand Javascript Codes for
     experiments.Started working on exp1 of colloid-and-surface-chemistry by
     creating simple page. Also looked for other ways to convert flash to javascript.
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Continued my work on experiment-1 lab
     colloid-and-surface-chemistry. Wrote javascript code based on video for experiment. 
   + [2017-06-06 Tue] - Continued my work on exp-1 for lab
     colloiid-and-surface-chemistry. Wrote  new functions for the experiment. 
   + [2017-06-07 Wed] - Continued my work on experiment one of my lab
     colloid-and-surface-chemistry. Wrote new functions and first experiment is
     almost done.
   + [2017-06-08 Thu] - Continued my work on exp-1 on lab
     colloid-and-surface-chemistry. Completed first Experiment. Read about some
     tools helpful for conversion of flash to java.
   + [2017-06-09 Fri] - As the 1st experiment was done, today I went through
     experiments of  Lab "physical-chemistry-iiith". I looked for some tools on
     net helpful for me and read about those tools. Also Presented our lab
     experiment to all in presentation Room.
** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]
   + [2017-06-12 Mon] - Today I searched for different tools on web that can
     make conversion easier. I read about "google web developer" which makes
     conversion into html5 easier and some other tools like  : Adobe
     Wallaby,Haxe,AS3JS. At Last I found a website "createjs.com" which has
     some libraries which can make animation work easier.
   + [2017-06-13 Tue] - Today I  started my work on exp-6 of lab physical-chemistry-iiith.
     I almost completed the Experiment. I also read about "createjs", this provides some libraries, 
     which makes conversion easier, I also watched tutorials on use of these libraries.
   + [2017-06-14 Wed] - Completed first experiment of "physical-chemistry-iiith" lab, and started 
     2nd experiment as well. Also read about some other libraries useful for conversion of flash to javascript.
   + [2017-06-15 Thu] - Completed second experiment of lab physical-chemistry-iiith. Also read about some new functions can be useful in animation.
   + [2017-06-16 Fri] - Added Comments to my Last 2 Experiments. Read about
     some new libraries on web. Presented my work in presentation.
** Week 4 [2017-06-19 Mon] till [2017-06-25 Sun]
   + [2017-06-19 Mon] - Started With 3rd Experiment of my lab. Read about some
     new functions and library (Velocity.js and so on).
   + [2017-06-20 Tue] - Completed 3rd experiment and Started 4th experiment of lab Physical-chemistry-iiith.
     Implemented Some new functions with help of library "velocityJs".
   + [2017-06-21 Wed] - Worked on  4rd experiment of lab Physical-Chemistry-iiith. wrote some new functions using
     "velocityJs library".
   + [2017-06-22 Thu] - Completed 4th & 5th experiment of lab physical-chemistry-iiith.Also Wrote test cases for all experiments.
   + [2017-06-23 Fri] - Started Writing test casees for experimen of lab "physical-chemistry-iiith". Also fixed some bug in experiments. Read about library "velocityJs" more on web.
** Week 5 [2017-06-26 Mon] till [2017-07-02 Sun]
   + [2017-06-27 Tue] - Started Experiment of lab colloid-surface-chemistry-iiith. Also completed writing test cases. And discussed about new lab kind of gaming engine.
   + [2017-06-27 Tue] - Continued my work on experiment-7 of lab  colloid-surface-chemistry-iiith. Fixed some bugs/errors in preious experiments.
   
   Approved. Lalit Mohan
   
   + [2017-06-28 Wed] - Coninued my work on experiment-7 of lab colloid-surface-chemistry iiith. tried to search for some good library for one animation in experiment-7, found that using svg animation can solve that problem easily. So read about svg images and tried to perform that animation,but wasn't able to do it correctly.
   
   + [2017-06-29 Thu] - Almost done with experiment-7 of colloid-surface-chemistry  iiith. Just need to add comments and naming of images are left(as good coding practise). Also started working on experiment-15 of lab colloid-surface-chemistry-iiith.
   
   + [2017-06-30 Fri] - just looked into my old experiments bcoz found some errors there. Also added comments for experiment-7 of colloid-surface-chemistry-iiith.  
   
** Week 6 [2017-07-03 Mon] till [2017-07-09 Sun]
   + [2017-07-03 Mon] - continued my work on experiment-15 of lab colloid-surface-chemistry-iiith.wrote new functions for this experiment. 
   
   + [2017-07-04 Tue] - almost completed my work on on experiment-15 of lab colloid-surface-chemistry-iiith, just need to write comments.
   
   + [2017-07-05 Wed] - done with comments and functionalities of experiment-15 of lab colloid-surface-chemistry. now done with almost every experiment.
   
   + [2017-07-06 Thu] - some bugs were there for experiment 7 & 15, so just fixed those bugs. Also talked to lalit sir for my research paper working,will start my work on writing paper from monday.
   
   + [2017-07-07 Fri] - testing of experiments of physical-chemistry-lab started, so resolved issuees raised. also started searching and reading about research paper which can write for my lab.

** Week 7 [2017-07-10 Mon] till [2017-07-16 Sun]
   + [2017-07-10 Mon] - as testing is going so just resolved issues for experiment-6 of lab physical-chemistry-iiith.Also discussed about my paper with lalit sir,understood how to start. he told me about  some research papers so started reading them and completed on paper of "yogesh maheshwari". he has used a different method for conversion. He used transcompilers for conversion, so read about that.
   
   + [2017-07-11 Tue] - testing of 7th expperiment of lab physical-chemistry-iiith finished, so resolved issues of that experiments. Also read 2 another research paper related to my work. also regarding my paper searched for different tools available on web like google swiffy, shumway etc.
   
   + [2017-07-12 Wed] - testing of 8th experiment is done so just fixed issues in that experiment.regarding paper read about structure of flash videos and structure of swf/fla files.
   
   + [2017-07-13 Thu] - testing of 6_10th experiment is done so resolved issues for that experiment.regarding my paper, started writing points for paper. Wrote abstract and introduction/motivation for paper. 
   
   + [2017-07-14 Fri] - testing of last experiment was done so fixed issues for that experiment. Regarding my paper, comntinued searching for contents also thought about poster.
