#+TITLE: Time sheet
#+AUTHOR: Kalpit Pokra
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

  

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Worked on setting up environments. Read the documentry
     regarding conversion to java script of flash to understand work.Then went through some experiments to understand
     how to work and tried to select lab and experiment as first task.
   + [2017-06-02] - Tried to Understand Javascript Codes for
     experiments.Started working on exp1 of colloid-and-surface-chemistry by
     creating simple page. Also looked for other ways to convert flash to javascript.
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Continued my work on experiment-1 lab
     colloid-and-surface-chemistry. Wrote javascript code based on video for experiment. 
   + [2017-06-06 Tue] - Continued my work on exp-1 for lab
     colloiid-and-surface-chemistry. Wrote  new functions for the experiment. 
   + [2017-06-07 Wed] - Continued my work on experiment one of my lab
     colloid-and-surface-chemistry. Wrote new functions and first experiment is
     almost done.
   + [2017-06-08 Thu] - Continued my work on exp-1 on lab
     colloid-and-surface-chemistry. Completed first Experiment. Read about some
     tools helpful for conversion of flash to java.
