#+TITLE: Time sheet
#+AUTHOR: Kalpit Pokra
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

  

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Worked on setting up environments. Read the documentry
     regarding conversion to java script of flash to understand work.Then went through some experiments to understand
     how to work and tried to select lab and experiment as first task.
   + [2017-06-02] - Tried to Understand Javascript Codes for
     experiments.Started working on exp1 of colloid-and-surface-chemistry by
     creating simple page. Also looked for other ways to convert flash to javascript.
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Continued my work on experiment-1 lab
     colloid-and-surface-chemistry. Wrote javascript code based on video for experiment. 
   + [2017-06-06 Tue] - Continued my work on exp-1 for lab
     colloiid-and-surface-chemistry. Wrote  new functions for the experiment. 
   + [2017-06-07 Wed] - Continued my work on experiment one of my lab
     colloid-and-surface-chemistry. Wrote new functions and first experiment is
     almost done.
   + [2017-06-08 Thu] - Continued my work on exp-1 on lab
     colloid-and-surface-chemistry. Completed first Experiment. Read about some
     tools helpful for conversion of flash to java.
   + [2017-06-09 Fri] - As the 1st experiment was done, today I went through
     experiments of  Lab "physical-chemistry-iiith". I looked for some tools on
     net helpful for me and read about those tools. Also Presented our lab
     experiment to all in presentation Room.
** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]
   + [2017-06-12 Mon] - Today I searched for different tools on web that can
     make conversion easier. I read about "google web developer" which makes
     conversion into html5 easier and some other tools like  : Adobe
     Wallaby,Haxe,AS3JS. At Last I found a website "createjs.com" which has
     some libraries which can make animation work easier.
   + [2017-06-13 Tue] - Today I  started my work on exp-6 of lab physical-chemistry-iiith.
     I almost completed the Experiment. I also read about "createjs", this provides some libraries, 
     which makes conversion easier, I also watched tutorials on use of these libraries.
   + [2017-06-14 Wed] - Completed first experiment of "physical-chemistry-iiith" lab, and started 
     2nd experiment as well. Also read about some other libraries useful for conversion of flash to javascript.
   + [2017-06-15 Thu] - Completed second experiment of lab physical-chemistry-iiith. Also read about some new functions can be useful in animation.
   + [2017-06-16 Fri] - Added Comments to my Last 2 Experiments. Read about
     some new libraries on web. Presented my work in presentation.
** Week 4 [2017-06-19 Mon] till [2017-06-25]
   + [2017-06-19 Mon] - Started With 3rd Experiment of my lab. Read about some
     new functions and library (Velocity.js and so on).
   + [2017-06-20 Tue] - Completed 3rd experiment and Started 4th experiment of lab Physical-chemistry-iiith.
     Implemented Some new functions with help of library "velocityJs".
   + [2017-06-21 Wed] - Worked on  3rd experiment of lab Physical-Chemistry-iiith. wrote some new functions using
     "velocityJs library".
