#+TITLE: Karthik Rao Timesheet
#+AUTHOR: Karthik Rao
#+DATE: [2017-06-01 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Automated openvz and cluster using ansible playbook in centos operating system
   
   + [2017-06-02 Fri] - Configured the network on the router and gave access to the internet.
           Aautomated installation of open ssh.
   
   
**  Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Read about elk stack which inturn means elasticsearch logstash and kibama.Elasticsearch is a juggernaut solution for your data extraction problems.Installed elk on the system and learnt the basics tools required for using kibama.

  + [2017-06-06 Tue] -Started working with kibama and logstash.Giving data to indices created and visualizing the graphs from the given data.Started working on importing data from external files(.txt fies) and visualising graphs for the given parameters in kibama.
+ [2017-06-07 Wed] - Visualised graphs for more than one parameter on X-axis using kibana. worked on converted a given text file to json format which can be given to kibama nd used for visualisation.
+ [2017-06-08 Thu] - Successfully coverted a given text file to json format using format and given the output json file to elasticsearch which inturn is connected to kibana.Visualized graphs for the some of the parameters in given through the text file using kibana.
+ [2017-06-09 Fri] - Started working on getting logs from the system using logstash. Tried converting text files to json files using logstash plugins.

* Month of July

