#+TITLE: Keshavs Time sheet
#+AUTHOR: Keshav
#+EMAIL: keshavkms@gmail.com ( 956-093-3318 ) 
#+DATE: [2017-06-01 Thursday]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Setting up the development environment. Researched
     various tools for constructing virtual labs including Org mode (OG),
     openModelica (OM), Light Table  (LT) and Jupyter Notebooks (JN). 
   + [2017-06-02 Fri] - Discussion with Maruthi sir,Lalit sirand Priya ma'am
     regarding the use cases of OpenModelica and the feasibility of using them
     in a virtual lab. Set up the work environment for OpenModelica framwork
     and transpilation to JS and read up on the relevant documentation.
     started working on a demo framework model to show the usefulness of
     openmodelica in a virtual environment.
   + [2017-06-03 Sat] 
   + [2017-06-04 Sun]

** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun] 
   + [2017-06-05 Mon] - Began writing scripts for setting up environment for
     creating modelica simulation models. Reverse engineering the script for
     converting modelica models to JS scripts to enhance customizability of the
     code and also automate the entire process from start to finish, so that
     given a model, it can generate a html div that can be embedded in a
     web page with very little modifications .
   + [2017-06-06 Tue] - Almost finished writing script for environment
     installation and generating models. Able to display model in a webpage,
     still working on simulating it.Documentation is absent so having to
     reverse engineer a lot of interfaces by trial and error.
   + [2017-06-07 Wed] - Finished work on generating models and wrote the
     interface code for simulating the model. Worked on fixing broken
     simulation links.Was unable to find links to the proper documentation in
     the OMC to figure out the source of the problem.Started work on reverse
     engineering the script code.Extended the expected deadline to Friday.
   + [2017-06-08 Thu] - Couldn't make any discernible progress today. Spent
     time working on resolving dependencies in the various scripts and writing
     glue code to patch everything up ,but still haven't ended up at a working
     prototype yet.functionally stuck at where i was yesterday.
   + [2017-06-09 Fri] - Tried to fix the Front end Node.Js requirement.Had the
     presentation today.Was suggested by maruthi sir to read back the modelica
     documentation . Started to work out a plan to work from scratch.    

** Week 3 [2017-06-12 Mon] till [2015-06-18 Sun]
   + [2017-06-12 Mon] - Was stuck at a major roadblock,decided to scrap the
     work and start over. recompiled the openmodelica and emscripten
     installation from scratch from the source code and manually verified paths
     to all the proper directories. ran all the sanity checks for the
     environment,and worked on fixing on fixing the few that failed.
     working on fixing non functional c compiler

* Month of July
