#+TITLE: Work Logs of MaheeSurya
#+AUTHOR: MaheeSurya
#+DATE: [2017-06-01 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad.

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Read the documentary regarding conversion of Flash
     simulations into JavaScript. Watched some Flash simulations to get a rough
     idea. Tried to understand a sample code which used JavaScript to run the
     simulation. Cloned the required repositories and installed the necessary
     tools required for the conversion. Need to understand the codes better to
     be able to write them efficiently.
   + [2017-06-02 Fri] - Tried to understand the JavaScript codes of
     Molecular-Absorption-Spectroscopy-Responsive-lab. Tried to implement a
     basic HTML version of Colloid-and-Surface-Chemistry lab Experiment-1. Used
     a Flash Decompiler to get all images of the swf file. Learned about Image
     Mapping which can be used in the work. Revised the documentation of the
     conversion of Flash into JavaScript.  
** Week 1 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Worked on converting Experiment-1 of
     Colloid-and-Surface-Chemistry lab. Worked on  CSS and JavaScript to get
     the required effect on the HTML page.
   + [2017-06-06 Tue] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. As some images required for the
     conversion were missing, I used screen-capture and extracted the frames of
     the video to get the necessary images. Later, cropped all the images and
     completed the task. I'm halfway through the conversion. Will try to
     complete the conversion of Experiment-1 by tomorrow.
   + [2017-06-07 Wed] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. I've completed 75% of the
     conversion. Will complete the conversion by tomorrow.
   + [2017-06-08 Thu] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. I've completed the conversion of the
     Experiment. But there are some minor errors which require attention. I'll
     rectify them and start working on another Experiment of
     Colloid-and-Surface-Chemistry lab by tomorrow.
