#+TITLE: Work Logs of MaheeSurya
#+AUTHOR: MaheeSurya
#+DATE: [2017-06-01 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad.

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Read the documentary regarding conversion of Flash
     simulations into JavaScript. Watched some Flash simulations to get a rough
     idea. Tried to understand a sample code which used JavaScript to run the
     simulation. Cloned the required repositories and installed the necessary
     tools required for the conversion. Need to understand the codes better to
     be able to write them efficiently.
   + [2017-06-02 Fri] - Tried to understand the JavaScript codes of
     Molecular-Absorption-Spectroscopy-Responsive-lab. Tried to implement a
     basic HTML version of Colloid-and-Surface-Chemistry lab Experiment-1. Used
     a Flash Decompiler to get all images of the swf file. Learned about Image
     Mapping which can be used in the work. Revised the documentation of the
     conversion of Flash into JavaScript.  
** Week 1 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon] - Worked on converting Experiment-1 of
     Colloid-and-Surface-Chemistry lab. Worked on CSS and JavaScript to get
     the required effect on the HTML page.
   + [2017-06-06 Tue] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. As some images required for the
     conversion were missing, I used screen-capture and extracted the frames of
     the video to get the necessary images. Later, cropped all the images and
     completed the task. I'm halfway through the conversion. Will try to
     complete the conversion of Experiment-1 by tomorrow.
   + [2017-06-07 Wed] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. I've completed 75% of the
     conversion. Will complete the conversion by tomorrow.
   + [2017-06-08 Thu] - Worked on the conversion of Experiment-1 of 
     Colloid-and-Surface-Chemistry lab. I've completed the conversion of the
     Experiment. But there are some minor errors which require attention. I'll
     rectify them and start working on another Experiment of
     Colloid-and-Surface-Chemistry lab by tomorrow.
   + [2017-06-09 Fri] - Worked on fixing some errors in Experiment-1 of
     Colloid-And-Surface-Chemistry lab. Added mouse pointers on hover to some
     objects. Read the documentary on svg images. Trying to explore other
     methods of conversion of flash to JavaScript.
** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]
   + [2017-06-12 Mon] - Worked on understanding different methods for the
     conversion of flash to javascript. Tried to learn about haxe and
     openfl. Also, I tried to explore Google Web Designer and CreateJS. Will
     try to decide a suitable way for the conversion by tomorrow.
   + [2017-06-13 Tue] - Watched some tutorials on CreateJS and OpenFl. I've
     decided to use CreateJS this time as could not understand how to use
     OpenFl in the conversion while Google Web Designer is only a tool for
     building a HTML page. Started working on Experiment-5.
   + [2017-06-14 Wed] - Working on conversion of Experiment-5 of
     Colloid-and-Surface-Chemistry lab. Trying a different approach provided in
     the documentary. About 20% of the conversion is completed. Need two more
     days for complete conversion. 
   + [2017-06-15 Thu] - Working on the conversion of Experiment-5 of
     Colloid-and-Surface-Chemistry lab. Unable to use CreateJS. Rolling back to
     previous method. Need two more days to complete the conversion.
   + [2017-06-16 Fri] - Working on the conversion of Experiment-5 of
     Colloid-and-Surface-Chemistry lab. Completed around 30% of the conversion.
** Week 4 [2017-06-19 Mon] till [2017-06-25 Sun]
   + [2017-06-19 Mon] - Working on the conversion of Experiment-5 of
     Colloid-and-Surface-Chemistry lab.Completed 50% of the conversion. Watched
     some tutorials on Velocity.js. Will complete the converion by
     Wednesday. I'm planning to use web-workers for multi-threading in
     JavaScript. So, I'm planning to convert a small experiment of
     Physical-Chemistry lab by using this concept. As I don't know much about
     the Web-Worker idea, I might fail in my attempt. So, I'm choosing a short
     experiment as even if I fail the experiment will be completed within the
     time. 
   + [2017-06-20 Tue] - Working on the conversion of Experiment-5 of
     Colloid-and-Surface-Chemistry lab. Completed 60% of the conversion. Stuck
     at the issue of simulating torch light. Will try to find a solution for
     the issue by tomorrow.
