#+TITLE: nikhil.org
#+AUTHOR: Nikhil Bansal
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Learned a bit about alloys and and alloy analyzer. Downloaded some docs and books pdf
                        related to alloys. 
                      - Read about linux shell ans commands.
                      - Read a slide related to software abstractions
   + [2017-16-02 Fri] 
                      - continued working on alloys and analyzer. Read some text on it.
                      - Read some research paper related to Linux shell and commands.
                      - Analyzed on how can easily make shell commands easy to interpret rather than just mugging.
                      - Thought about JS shell so that student can get info about hovering on shell commands.                      
                                          
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon]
     - Gathered Some resources to learn linux shell and commands
       - [[http://ryanstutorials.net/linuxtutorial/]] - For begineers(great tutorial and very well explained)
       - [[https://www.tutorialspoint.com/unix/]] - for begineers to learn from basics
       - [[http://linuxcommand.org/learning_the_shell.php]]
       - [[https://www.linux.com/news/how-learn-unixlinux]]
    -  worked on getting the old linux-lab run
       - As the whole lab had been made using php framework. I have started learning php using
         - [[https://www.w3schools.com/php/]]
         - [[https://www.codecademy.com/learn/php]]
       - Installed php7 on my system using commands
         - =sudo apt-get update=
         - =sudo apt-get install php7.0=
       - Tried understanding and debugging the code. This took most of time
       - After diving into the code of old-lab i found out that i need to do web-app-short course again, so, i did it again.   
   + [2017-06-06 Tue]
     - Continued debugging the code of linux lab and learning php
     - I debuged the code of linux-lab and that took most of the time 
     - Minutes of meeting with mentor
       - Todo     
         - termlib.js (search the term)
         - search about browser terminal (i.e terminal on browser(frond-end virtual-box type to execute commands with some kind of filter) and backend local-server)
         - We can hover over command outputs on virtual-box to see details of the output. 
         - Final architecture of design of linux-lab will be discussed in 1-2 days 
   + [2017-06-07 wed]
     - Searched for the termlib.js and found that:-
       - It is a JS library that provides a terminal obgect, which falicitates a simple and object oriented approach to generate and control a terminal like interface.
         - [[http://www.masswerk.at/termlib/]] - resource 
         - example:-
                   #+BEGIN_SRC 
                    var term = new Terminal( {handler: termHandler} );
                    term.open();

                    function termHandler() {
                      this.newLine();
                      var line = this.lineBuffer;
                      if (line != "") {
                        this.write("You typed: "+line);
                      }
                      this.prompt();
                    }
                   #+END_SRC  
     - Searched for browser terminal and found some great examles
       - [[https://www.codecademy.com/courses/learn-the-command-line/lessons/navigation/exercises/pwd?action=lesson_resume]] - A terminal implented like on browser
         - On testing this terminal a found that lacks filter for commands
           eg- I can do =rm -rf /= which can delete the files of whole system.
         - It lacks hovering on output of commands for info
     - I thought about how to implement terminal on browser
       - First  I need to make a directory in which user can do whatever he wants
       - I need to add filters through js so to restrict user to this directory only.
       - I need to convert the convert the command typed on browser and execute it on machine and display the output on browser.
   
   + [2017-06-08 Thr]
     - Read the documentation of older linux lab.
       - Some problems encountered with this linux lab
         - The current state of the problem is that the communication between the Linux lab and ldap server is not happening properly.
         - ldapscripts called from the linux lab are not able to register user in the ldap server.
         - The communication between gateone server and ssh is not established.
       - Working 
         1. User visits the virtual lab webpage
         2. The webpage loads some scripts
         3. The script makes a connection to backend 'Gateone' gateway server using WebSockets
         4. The gateway server then connects to a backend SSH server via the SSH protocol
         5. The gateway server also emulates a terminal to the SSH server
         6. The contents of the emulated terminal are sent to the user's web page and get displayed
         7. All the user's input is forwarded via the gateway the SSH server
         8. For security, there are several limitations put up on the user's account in the restricted shell SSH server
         9. The user account information comes from an OpenLDAP server setup separately
         10. Accounts on the OpenLDAP server get created when the user registers for virtual labs
         11. Home directories for the user's are on a NFS mount which is served by a central NFS server with quotas setup 
   + [2017-07-08 Fri]
      - Most of the time out for weekly presentation
      - Points raised during presentation are :-
        - Discuss every thing with your mentor and asked all your doubts.
        - Think of new ideas of improving lab and discuss it with your mentor.
        - Don't do anything that is already available. Think of something new.
* Month of July
