#+TITLE: Time sheet
#+AUTHOR: Projit Bandyopadhyay
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad



* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-02 Fri]
   + [2017-06-01 Thu] - Worked on setting up development environment. Discussed
     requirements for the Authentication between VLEAD Services. For rest of
     week need to work on surveying current industrial standards for this type
     of authentication. Created survey.org document and have looked through
     resources to use. JWT seems to be the best option(Have pushed analysis and
     advantages for it) for implementing the requirements but I think our
     mentors want to to integrate with Oauth, need to find out exact scope
     and requirements for this project.
   + [2017-06-02 Fri] - Went through JWT documentation and implementation. JWT
     seemed to be the best way to authorize microservices in my opinion. Had a
     discussion Maruthi Sir, which led to further clarification on the scope of
     my project. It seems I'm supposed to build a service similar to oauth,
     which will allow a user to "login using vlab account" into the various
     labs. This would involve server-server flows. The other flows would be
     handled later like: reduce need for user to keep clicking login buttons
     when a lab is located in a different server. * Need to get confirmation
     from Thirumal Sir whether this is the actual scope of my project, if so,
     more resources may be required or the expectations would need to be clearly defined.

** Week 2 [2017-06-05 Mon] till [2017-06-09 Fri]
   + [2017-06-05 Mon] - Went through further documentation on Oauth 2.0. Had an
     extensive meeting with Thirumal Sir to evaluate what the project actually
     entails. Conclusion was to make a prototype of the authorization using
     JWT. Further clarification on the scope of the project was also
     received. Did further work on creating a plan for the work-flow and
     setting deadline. Also did further research on JWT to see its use in small
     applications. Need to setup outreach portal application to start
     integrating new auth system(to be built)
   + [2017-06-06 Tue] - Worked on setting up the outreach portal
     application. Encountered some problems and bugs on setup which Sripathi is
     trying to fix. Met with Akash to discuss security related problems on JWT
     implementation. After further research and analysis, decided that JWT is
     not the method of implementation we will be using. The scope of the
     project has again been redefined to making an Oauth service. Currently the
     outreach portal uses a login with Google. Aim is to make login with vlabs.
   + [2017-06-07 Wed] - Did research on different open source implementations
     of oauth service. Found that most of the solutions are in Java. Created a
     document with links to all the implementations I found. Currently working
     on using a django based implementation to create the service. Have created
     the login and sign up of the user today. Will work on integrating the
     oauth elements from tomorrow.
   + [2017-06-08 Thurs] - Went through possible implementations of the oauth
     service. Two possible ways: implementing from almost scratch using django
     or using a blackbox java version(present in documentation). Hit a
     roadblock in the django implementation with redirect URIs. Also
     helped(unsuccessfully) figure out how to compile OpenModelica scripts. Will
     explore the java blackbox alternative tomorrow.
   + [2017-06-09 Fri] - Organized directory structure to comply with norms and
     vlabs makefile. Presented various findings and failures. Discussed to
     great extent the implications of creating an oauth service. The mentors
     agreed that this would be very difficult to create. Maruthi Sir suggested
     I continue to go through the oauth documentation, and that implementations
     in node are preferred over all. I currently have found an implementation
     in node and will be looking into it from next week. Also need to have
     further discussions to understand and get help to create this project.
** Week 3 [2017-06-12 Mon] till [2017-06-16 Fri]
   + [2017-06-12 Mon] - Read further on oauth documentation, and created notes
     on different parts of the implementation that would be required by
     us. Created a diagram to show to flow of tokens in the system. Also
     contributed to helping out other mentors with some javascript work, as I
     was waiting for clarification from Thirumal Sir on how to approach the
     project going forwards.
   + [2017-06-13 Tue] - Met with Thirumal Sir to discuss the project. Ideas
     that came up include: looking at gitlab source code to see implementation
     of their auth service, and looking at flask implementations(found
     online). Worked on testing one flask server(successfully except for a
     small bug on the final view response. But the passing of credentials is
     correct.). Will take a look at other implementations too. Also attended a
     talk on renarration at the end of the day.
   + [2017-06-14 Wed] - Worked on fixing the flask server today. Met with
     maruthi sir and discussed the flow and how to conceptualize oauth2 user
     flow. Figured out how to run both example servers(was proxy issue) and was
     able to run them once. However currently unable to replicate results so
     will work on that tomorrow.
   + [2017-06-15 Thurs] - Figured out how to run the example severs multiple
     times(issue with logout, has been documented). Worked on further
     documentation of things done so far, creating diagrams and explanations.
   + [2017-06-16 Fri] - Presented my findings. Had a meeting with Chopella Sir,
     Akash, and Thirumal Sir. We discussed alternative ideas in my project like
     outsourcing the authentication server to some provider. Will clarify
     scope(possibly new) on Monday.
  
     
   
