#+TITLE: Time sheet
#+AUTHOR: Projit Bandyopadhyay
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-2.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad


  
* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-02 Fri]
   + [2017-06-01 Thu] - Worked on setting up development environment. Discussed
     requirements for the Authentication between VLEAD Services. For rest of
     week need to work on surveying current industrial standards for this type
     of authentication. Created survey.org document and have looked through
     resources to use. JWT seems to be the best option(Have pushed analysis and
     advantages for it) for implementing the requirements but I think our
     mentors want to to integrate with Oauth, need to find out exact scope
     and requirements for this project.
   + [2017-06-02 Fri] - Went through JWT documentation and implementation. JWT
     seemed to be the best way to authorize microservices in my opinion. Had a
     discussion Maruthi Sir, which led to further clarification on the scope of
     my project. It seems I'm supposed to build a service similar to oauth,
     which will allow a user to "login using vlab account" into the various
     labs. This would involve server-server flows. The other flows would be
     handled later like: reduce need for user to keep clicking login buttons
     when a lab is located in a different server. * Need to get confirmation
     from Thirumal Sir whether this is the actual scope of my project, if so,
     more resources may be required or the expectations would need to be clearly defined.

** Week 2 [2017-06-05 Mon] till [2017-06-09 Fri]
   + [2017-06-05 Mon] - Went through further documentation on Oauth 2.0. Had an
     extensive meeting with Thirumal Sir to evaluate what the project actually
     entails. Conclusion was to make a prototype of the authorization using
     JWT. Further clarification on the scope of the project was also
     received. Did further work on creating a plan for the work-flow and
     setting deadline. Also did further research on JWT to see its use in small
     applications. Need to setup outreach portal application to start
     integrating new auth system(to be built)
   + [2017-06-06 Tue] - Worked on setting up the outreach portal
     application. Encountered some problems and bugs on setup which Sripathi is
     trying to fix. Met with Akash to discuss security related problems on JWT
     implementation. After further research and analysis, decided that JWT is
     not the method of implementation we will be using. The scope of the
     project has again been redefined to making an Oauth service. Currently the
     outreach portal uses a login with Google. Aim is to make login with vlabs.
   + [2017-06-07 Wed] - Did research on different open source implementations
     of oauth service. Found that most of the solutions are in Java. Created a
     document with links to all the implementations I found. Currently working
     on using a django based implementation to create the service. Have created
     the login and sign up of the user today. Will work on integrating the
     oauth elements from tomorrow.
   + [2017-06-08 Thurs] - Went through possible implementations of the oauth
     service. Two possible ways: implementing from almost scratch using django
     or using a blackbox java version(present in documentation). Hit a
     roadblock in the django implementation with redirect URIs. Also
     helped(unsuccessfully) figure out how to compile OpenModelica scripts. Will
     explore the java blackbox alternative tomorrow.
   + [2017-06-09 Fri] - Organized directory structure to comply with norms and
     vlabs makefile. Presented various findings and failures. Discussed to
     great extent the implications of creating an oauth service. The mentors
     agreed that this would be very difficult to create. Maruthi Sir suggested
     I continue to go through the oauth documentation, and that implementations
     in node are preferred over all. I currently have found an implementation
     in node and will be looking into it from next week. Also need to have
     further discussions to understand and get help to create this project.
** Week 3 [2017-06-12 Mon] till [2017-06-16 Fri]
   + [2017-06-12 Mon] - Read further on oauth documentation, and created notes
     on different parts of the implementation that would be required by
     us. Created a diagram to show to flow of tokens in the system. Also
     contributed to helping out other mentors with some javascript work, as I
     was waiting for clarification from Thirumal Sir on how to approach the
     project going forwards.
   + [2017-06-13 Tue] - Met with Thirumal Sir to discuss the project. Ideas
     that came up include: looking at gitlab source code to see implementation
     of their auth service, and looking at flask implementations(found
     online). Worked on testing one flask server(successfully except for a
     small bug on the final view response. But the passing of credentials is
     correct.). Will take a look at other implementations too. Also attended a
     talk on renarration at the end of the day.
   + [2017-06-14 Wed] - Worked on fixing the flask server today. Met with
     maruthi sir and discussed the flow and how to conceptualize oauth2 user
     flow. Figured out how to run both example servers(was proxy issue) and was
     able to run them once. However currently unable to replicate results so
     will work on that tomorrow.
   + [2017-06-15 Thurs] - Figured out how to run the example severs multiple
     times(issue with logout, has been documented). Worked on further
     documentation of things done so far, creating diagrams and explanations.
   + [2017-06-16 Fri] - Presented my findings. Had a meeting with Chopella Sir,
     Akash, and Thirumal Sir. We discussed alternative ideas in my project like
     outsourcing the authentication server to some provider. Will clarify
     scope(possibly new) on Monday.
  
** Week 4 [2017-06-19 Mon] till [2017-06-13 Fri]
   + [2017-06-19 Mon] - Was reading through Flask Oauthlib to see documentation
     of the library and start implementing the authentication server. Then had
     a long meeting with Chopella Sir, Thirumal Sir,Akash, and Maruthi Sir to
     determine the use of creating our authentication server. Current
     conclusion stands at using Google's free registration of client
     applications to register our services and try to create the triangle
     structure discussed. Have looked through developer's console given by
     google which allows authentication of users(i think). Need to look for the
     services equivalent of this.
   + [2017-06-20 Tue] - Went through the LDS dashboard documentation. Also went
     through google oauth documentation to see requirements to register an
     application with their services(LDS had some documentation but it wasn't
     sufficient). Will register some applications tomorrow and start building
     the cluster. Was still not able to find proper documentation on
     registering service.
   + [2017-06-21 Wed] - Went through documentation for google's oauth. Also
     registered an app but functionality issues persist. Went through Chapter 9
     of book on microservices and created notes for it. Evaluated different
     proposals given in it. The book and the notes are listed as a closed issue
     in this repo.
   + [2017-06-22 Thurs] - Tried registering applications on google. Encountered
     some issues. Tried to install the lds dashboard but again encountered
     errors. Researching into google service accounts: current conclusions are
     that they can be used for server-server interactions between google and us
     but not between two of our accounts. Even the specified interactions do
     not meet our requirements.
   + [2017-06-23 Fri] - Did not work on authentication today. Worked on
     evaluating different publishing tools. Went through olabs(Amrita), to try
     and see how they have created their own labs. Looked at other examples
     like nicely made animations by colorado state university. Will try to
     reach out to the makers of the animations. Also experimented with GDevelop
     software used to make games. Created a simple game which shows that things
     created using this software can be easily integrated with the
     browser. Further scaling needs to be looked at it.
     
** Week 5 [2017-06-27 Tue] till [2017-06-30 Fri]
   + [2017-06-27 Tue] - Project is officially now to work on lab authoring
     tools. Created and configured the new repository with norms. Looked
     through different tools online notably: Molecular Workbench, PHET, CMU's
     virtual lab. Wrote about Molecular Workbench and its potential. JNLP seems
     to be a viable solution for other issues encountered. Discussed
     programming model for creating the tools and potential to collaborate with
     those working on conversion of flash labs to javascript.
   + [2017-06-28 Wed] - Worked on creating documentation of findings so
     far. Documented yesterday's meeting, set requirements for the
     project. Looked further through Molecular Workbench and viability,
     documenting findings as I go. Had a meeting with Maruthi Sir about oauth
     and lab authoring tools. He gave many different resources to look at. We
     also clarified our end goals of the project. His thought process was
     towards making very elegant simulations that could be used almost at a
     professional level. We should check places from where we could source our
     experiments as high quality ones are available online.
   + [2017-06-29 Thurs] - Continued work on documentation regarding different
     modeling and simulation softwares. Three sections for each: About,
     Features, and My Analysis. 5-6 softwares still remaining to go through,
     should be done tomorrow.
   + [2017-06-30 Fri] - Finished work on documentation of different simulation
     and modeling software. Also prepared a presentation as I was supposed to
     present(postponed to later). Tried to setup a meeting with some of our
     seniors to assist with graphics inputs regarding this project. Also
     discussed idea of integration with other non-profit and social education
     ventures. 
* Month of July
** Week 6 [2017-07-03 Mon] till [2017-07-07 Fri]
   + [2017-07-03 Mon] - Worked on creating a simple interface using html and
     javascript to display a box, and move and place it anywhere on the
     screen. Also added the ability to add new boxes to the screen. Also worked
     on simulating attacks on different services. Was able to extract icon from
     khanacademy(determining if user is logged in). Also found critical bug in
     google, which allows us to log a user out of all google services from our
     attack site.
   + [2017-07-04 Tue] - Made the code of the simple box display more modular so
     that it can be edited effectively. Also experimented with changing the
     sizes of the boxes(successfully). Then worked on fixing the attack site
     and find new sites to attack. Found that outlook not vulnerable to logout
     but khanacademy is. Worked on further clickjacking and csrf
     attacks. Managed to carry out logouts on sites like uber, sbi, skype.
   + [2017-07-05 Wed] - Tried(unsuccessfully) to use an image instead of a
     regular box in the display. Worked on continuing csrf attacks on
     logout. IOB net banking was also found to be vulnerable to this kind of
     attack. Also updated paper structure and looked into different versions of FIM.
   + [2017-07-06 Thurs] - Made changes to the movement in box. Can now upload
     an image url and it will display that image in the box. That image can
     then be moved around in the box and placed at any point(could potentially
     be used by other groups to get coordinates of where to place
     images). Carried out google logout attack in proper format with screenshots.
   + [2017-07-07 Fri] - Carried out the rest of the attacks with proper
     documentation. Created outline for paper. Tried to resize images uploaded
     into the frame. Was able to either resize or move not both simultaneously.

** Week 7 [2017-07-10 Mon] till [2017-07-14 Fri]
   + [2017-07-10 Mon] - Continued to try working on the resizing of images. Met
     with Akash to layout paper format and further goals. Researched shibboleth
     and wrote about it as well. Also looked a bit into pygame (potential for
     lab authoring tools). Will clean up the documentation of authoring tools
     so far tomorrow.
   + [2017-07-11 Tue] - Read more on pygame. Worked on the paper, writing about
     Shibboleth(which was cancelled in the end). Also wrote on other 
     areas.
   + [2017-07-12 Wed] - Worked mainly on the paper today. Condensed images
     together to form a single image to decrease need for space. Also filled in
     missing text in various locations(connecting sentences and introductions
     to different sub-parts). Created a table that shows service, FIMs used,
     logout url. Also wrote about SAML. Worked out a plan for completing the
     writing part of the rest of the paper. Hopefully writing will be complete
     as of end of tomorrow, and we can start condensing from Friday.
   + [2017-07-13 Thurs] - Worked on more writing for the paper. Wrote the
     Introduction for the paper along with some other lines required in various
     places of the paper
   + [2017-07-14 Fri] - Worked on writing the paper as well as starting
     creating the poster to be presented next week. Wrote the Cross-site timing
     attack part as well as condensed images for it's mitigation. Also worked
     on documentation in the lab authoring tools. 

     
