#+TITLE: Time sheet
#+AUTHOR: Projit Bandyopadhyay
#+DATE: [2017-06-01 Thurs]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad



* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - Worked on setting up development environment. Discussed
     requirements for the Authentication between VLEAD Services. For rest of
     week need to work on surveying current industrial standards for this type
     of authentication. Created survey.org document and have looked through
     resources to use. JWT seems to be the best option(Have pushed analysis and
     advantages for it) for implementing the requirements but I think our
     mentors want to to integrate with Oauth, need to find out exact scope
     and requirements for this project.
  +  [2017-06-02 Fri] - Went through JWT documentation and implementation. JWT
    seemed to be the best way to authorize microservices in my opinion. Had a
    discussion Maruthi Sir, which led to further clarification on the scope of
    my project. It seems I'm supposed to build a service similar to oauth,
    which will allow a user to "login using vlab account" into the various
    labs. This would involve server-server flows. The other flows would be
    handled later like: reduce need for user to keep clicking login buttons
    when a lab is located in a different server. * Need to get confirmation
    from Thirumal Sir whether this is the actual scope of my project, if so,
    more resources may be required or the expectations would need to be clearly defined.
