#+TITLE: Work Logs of all interns
#+AUTHOR: VLEAD
#+DATE: [2017-06-02 FRI]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad.

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu]
    - Get updated with the progress of renarration project.
    - Go through HLD docs.
    - Discuss about database implementation and design for the project.
   + [2017-06-02 Fri] - [2017-06-03 Sat]
    - Go through remaining docs.
    - started working on video annotation system
    - meeting with Prof. Choppella regarding the present status of work for targetting the upcoming workshop.
    - Explored MongoDB PyMongo for NoSQL implementation of SSS-Database.
 
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
  + [2017-06-05 Mon]
    - Had a meeting with Sai sir. Discussed about the concept and implementation of SSS project.
    - Sai sir create a repo =SSS-Database= which contains literate documents and implementation for persistance part.
    - Explored free MongoDB as a service platforms available. Found mlabs(as suggested by Soumya) and Mongo Altlas.
    - Finalized with Mongo Atlas for now because it works with latest version of mongoDB i.e. v3.4.4 and provides 0.5 GB of space with replicas on 2 more servers.
    - Made a protoype to understand the functionality of Mongo Atlas using PyMongo.
    - Also deployed a small python app on heroku for learning purpose. Will try to talk with MongoAtlas using heroku later sometime.
    - Had meeting with Prof. Venkatesh sir, Soumya, Sadhana and Sai sir about the concept of renarration project and also discussed about upcoming workshop and its schedule.
    - Finalized the dates for integration, deployement, testing and workshop rehearsal.
  + [2017-06-06 Tue - 2017-06-07 Wed]
    - Had meeting with Sai sir. We discussed about the datamodel which is to be made in MongoDB.
    - Desinged a RESTful API which will be used to talk with SSS-Maker and SSS-Renderer and MongoDB Atlas cloud.
    - Built the proposed API in flask. Faced some difficulties like in choosing the best suited library for the implementation. Libraries which I tried are MongoEngine, MongoAlchemy, PyMongo and Eve Framework. All of them consist of PyMongo. I choosed PyMongo for implementation because it gives a lot of flexibility and control over database operations. I found other libraries less flexible but surely they are more robust and better tested prebuilt functions. Will look forward to use one of these but for now we have less time to put into backend aesthetics.
  + [2017-06-08 Thur]
    - Write functions for all the API endpoints.
    - *TODO* Write test cases and automated test functions.
    - *Explore possiblities in other libraries for MongoDB.
    - *TODO* Create user login form.
    - Complete the docs.
  + [2017-06-09 Fri]
    - Lost some work due to wrong git command while trying to unstage changes. =git clean -f= removed everything from local directory.
    - Sometimes its good to lose. Came up with a much better design. Present design follows OOP concepts and gives more functionality to user.
** Week 3 [2017-06-12 Mon] till [2017-06-17 Sat]
  + [2017-06-12 Mon]
    - Meeting with TB Dinesh Sir
      - Discussed about available open source tools for renarration and annotation.
      - How we can integrate it with our project.
      - Dr. Choppella also hinted to me that I can also convert this into my project for 6 months and make a fully fledged software product out of it.
      - Dinesh sir discussed about the following tools: 'narrows story teller', 'pandora', 'padma tool', 'Hyperaudio.io'.
  + [2017-06-13 Tue]
   - Worked on RESTful API. Its nearly complete now.
   - Attended a talk by TB Dinesh Sir on "renarrations".
   - Made classes more flexible.
  + [2017-06-14 Wed to 2017-06-15 Fri]
    - Documenting the work done by me till now.
    - TODO Writing tests for RESTful API
  + [2017-06-16 Sat]
    - Meeting with Sai Sir on Saturday to discuss about proposed semantic markup model.
    - Discussed about architecture of such model and use cases
    - Met Sai sir and finalized my task for this week.
** Week 4 [2017-06-19 Mon] till [2017-06-24 Sat]
  + [2017-06-19 Mon] 
    - I have to create a renderer which can perform transformations on DOM level, that is node level or element level.
    - I am required to make a system using which a user could attach different action to a specific DOM element and store them in sequence. So that it can be applied in sequence when retreived.
    - Wrote some inital docs regarding the implementation details.
    - I found this task very similar to features implemented in annolet and I can use that code here also.
  + [2017-06-20 Tue] - [2017-06-21 Wed]
    - New task assigned. Have to build a renderer for rendering Javascript binded with specific DOM elements. I am calling it =DOM-Manip= project.
    - Did some research and found out that I can use Annolet functions here.
    - Gone through webapp short course on recommandation of Venkatesh sir.
    - Created literate doc structure.
    - Converting earlier work into literate docs.
+ [2017-06-22 Thur]->[2017-06-23 Fri]
    - setup literate docs for code review.
    - met Sai sir to discuss and clear doubts regarding current task of DOM manipulation.
    - met Saumya mam to clear doubts regarding literate docs and makefile.
    - created docs by following the web app short course.
** Week 5 [2017-06-26 Mon] till [2017-06-30 Sat]
  + [2017-06-27 Tue]->[2017-06-28 Wed]
    - Met Sai sir, discussed idea of DOM manipulation.
      - discussed about creating a DOM from elements given by a user.
      - Making a renderer which is generic in nature unlike present =sss-renderer= which focuses on NPTEL.
      - discussed about the research paper on DOM manipulation.
      - Introduced me to [[http://visualdataweb.de/webvowl/][WebVOWL]] which could be used to vizualize ontologies. Such as showing GATE exam syllabus. If done, we can think about publishing a paper in conference called [[http://www.mike.org.in/2017/][MIKE 2017]] which is about knowledge engineering.
    - Faced issue in sending request to REST API using python server hosted on other port.
      - Solved: Talked to Sripathi sir. He figured that our team was hosting servers on =127.0.0.1= which is not a public IP and hence cannot be reached via a other server. Changed IP to =0.0.0.0= which is a public IP and things worked fine.
    - Debugged =sss-renderer= code. Proper JSON document format was not followed as declared in =SSS-Format= doc.
    - By end of Tuesday, =sss-store= and =sss-renderer= were integrated partially with few bugs which were solved on Wednesday by Sadhana V..
    - Integration with =sss-maker= still remaining.
    - Started writing test-cases for =sss-store= using ~unittest~ package.
    - Got access to base4 machine. Setting up =sss-store= API server on =sss-persistence= container.
    - Potential issue: mongodb cloud may create error when while sending requests to it from base4 machine.
    - will try to setup mongodb instance inside =sss-persistence= container.
    - created issue on gitlab regarding deployment of gaurds and filters in =sss-persistence= repo.
    - created issue on gitlab regarding writing test cases in =sss-persistence= repo.

* Month of July
** Week 1 [2017-07-03 Mon] till [2017-07-07 Fri]
+ [2017-07-03 Mon]
    - All hands meet with Dr. Choppella at 9AM
      - Discussed about work culture of VLEAD
      - Opportunities for research assistants -> can publish our paper if we burn enough oil in our work.
      - Each one has to present a poster on 20th July, 17 regarding the work we have done so far.
      - Instructions given to be more punctual and professional towards work.
   - Meeting with Sai Sir
     - Discussed about the challenges in adding semantic tagging to current datamodel of =SSS-Framework=.
      - required contaxts for `sss-info`,`env-info` and `eventlist` are not available on =schema.org=.
     - Discussed about DSL for project and I described him the roadmap which I prefer to take:
      - Instead of writing DSL first, I will start from development of small functions to achieve very specific tasks, like grabing an element from DOM and shifting it to another postition at new xpath.
      - doing some kind of CRUD operations on an element.
     - Then we can think of making a DSL for same. In the meantime I will also revise the concepts of Context Free Grammer and Parsers.
     - He gave me a basic requirements structure which will help me in efficiently working towards the goals.
  - Compeleted the Semantic structure of data model. Few properties may be wrongly placed but I have tried my best to do the justice with existing structure with whatever contexts and properties were available on =schema.org=.
  - Saw two tech talks on DSL and parsing.
  - Integration of =SSS-Maker=, =SSS-Renderer= and =SSS-Persistence= is successfully done and deployed on base4 containers.+ 
+ [2017-07-04 Tue]
  - Meeting with Venkatesh Sir
    - It was about making =sss= project more generic.
    - user should be able to custom transcripts to a video
      - add questions or notes
      - add links
    - and all this should be addressable.
    - These will add more usecase to the project.
    
  - wrote explanation for Semantic structure and mailed to Sai sir.
  - Read APSEC paper written to be published on 7th July.
    - It helped me in figuring out the requirements for DSL.
  - met Sai sir and discussed about the implementation timeline for DSL.
  - For now I will start by creating 12 atomic functions for CRUD on Content, Behaviour and Presentation.
  
+ [2017-07-05 Wed]->[2017-07-06 Thur]
  - Compeleted development of 10 functions.
  - Testing of 5 functions done.
  - Some challanges faced
    - Which to choose, returning an error to calling function or throwing error right when it occured.
    - How to check if user has given a valid Javascript to add it to DOM node
    - How to check if a user has given valid CSS input to insert into DOM node.
    - How much testing should be done? Because I observed that some testcases go in too much details that they start coinciding with testcases for other functions.

+ [2017-07-07 Fri]
  - created highlighting tool using first set of functions.

** Week 2 [2017-07-10 Mon] till [2017-07-14 Fri]
+ [2017-07-10 Mon] -> [2017-07-11 Tue]
  - met Sai sir and Shridaran sir
    - Discussed about the goals we are trying achieve using DSL
      - DSL should be easy to understand and learn because it is created for technically illitrate users.
    - DSL should come much later in the development pipeline.
    - First we have to create all the related functions.
    - Idea of Service oriented architecture and Aspect oriented programming was also tossed.
    - I argued about the idea of converting all the features as webservice and then creating DSL over it.
    - Ideally webservices are independent of each other and don't share any functionality but in our case, nearly all the tools which we will be building will share many common functions like CRUD operation functions.
    - We finalized to focus on development of a working model for now and DSL will come later on.
  
+ [2017-07-12 Wed]
  - Read complete paper on DSL for renarration which is co-authored by Sai sir.
  - Met Venkatesh Sir and he asked about the status of video annotation tool. He want it to be completed within one week.
   - Also discussed about the notion of visual DSL which was strongly rejected by Venkatesh sir given the reason that there is scarecity of visual DSL tools.
    - He instructed me to demo virtual labs for music which was part of Tejaswinee's and Annon's project.
    - I have to drop a mail to Tejaswinee to ask her about revival of this website by removing persona login.
  - Met Sir sir and discussed about the exact requirements on which I have to build the system.
    - Finalized on the work expected from me to be done by this week and next.
 
