#+TITLE: Work Logs of all interns
#+AUTHOR: VLEAD
#+DATE: [2017-06-02 FRI]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad.

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu]
    - Get updated with the progress of renarration project.
    - Go through HLD docs.
    - Discuss about database implementation and design for the project.
   + [2017-06-02 Fri] - [2017-06-03 Sat]
    - Go through remaining docs.
    - started working on video annotation system
    - meeting with Prof. Choppella regarding the present status of work for targetting the upcoming workshop.
    - Explored MongoDB PyMongo for NoSQL implementation of SSS-Database.
 
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
  + [2017-06-05 Mon]
    - Had a meeting with Sai sir. Discussed about the concept and implementation of SSS project.
    - Sai sir create a repo =SSS-Database= which contains literate documents and implementation for persistance part.
    - Explored free MongoDB as a service platforms available. Found mlabs(as suggested by Soumya) and Mongo Altlas.
    - Finalized with Mongo Atlas for now because it works with latest version of mongoDB i.e. v3.4.4 and provides 0.5 GB of space with replicas on 2 more servers.
    - Made a protoype to understand the functionality of Mongo Atlas using PyMongo.
    - Also deployed a small python app on heroku for learning purpose. Will try to talk with MongoAtlas using heroku later sometime.
    - Had meeting with Prof. Venkatesh sir, Soumya, Sadhana and Sai sir about the concept of renarration project and also discussed about upcoming workshop and its schedule.
    - Finalized the dates for integration, deployement, testing and workshop rehearsal.
  + [2017-06-06 Tue - 2017-06-07 Wed]
    - Had meeting with Sai sir. We discussed about the datamodel which is to be made in MongoDB.
    - Desinged a RESTful API which will be used to talk with SSS-Maker and SSS-Renderer and MongoDB Atlas cloud.
    - Built the proposed API in flask. Faced some difficulties like in choosing the best suited library for the implementation. Libraries which I tried are MongoEngine, MongoAlchemy, PyMongo and Eve Framework. All of them consist of PyMongo. I choosed PyMongo for implementation because it gives a lot of flexibility and control over database operations. I found other libraries less flexible but surely they are more robust and better tested prebuilt functions. Will look forward to use one of these but for now we have less time to put into backend aesthetics.
  + [2017-06-08 Thur]
    - Write functions for all the API endpoints.
    - *TODO* Write test cases and automated test functions.
    - *Explore possiblities in other libraries for MongoDB.
    - *TODO* Create user login form.
    - Complete the docs.
  + [2017-06-09 Fri]
    - Lost some work due to wrong git command while trying to unstage changes. =git clean -f= removed everything from local directory.
    - Sometimes its good to lose. Came up with a much better design. Present design follows OOP concepts and gives more functionality to user.
  + [2017-06-12 Mon]
    - Meeting with TB Dinesh Sir
      - Discussed about available open source tools for renarration and annotation.
      - How we can integrate it with our project.
      - Dr. Choppella also hinted to me that I can also convert this into my project for 6 months and make a fully fledged software product out of it.
      - Dinesh sir discussed about the following tools: 'narrows story teller', 'pandora', 'padma tool', 'Hyperaudio.io'.
  + [2017-06-13 Tue]
   - Worked on RESTful API. Its nearly complete now.
   - Attended a talk by TB Dinesh Sir on "renarrations".
   - Made classes more flexible.
