#+TITLE: Worklog of Sunandan
#+AUTHOR: Sunandan Raj Pullagura
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of May
** Week 1 [2017-05-10 Wed] till [2017-05-14 Sun]
   + [2017-05-10 Wed] - Configured laptop as per the requirement for work environment.We were given material to study different languages required throughout the internship period.Started learning with racket language.Installed racket and studied the material for today
   + [2017-05-11 Thurs] - Learned racket and started doing assignment-1 and Completed the assignment
   + [2017-05-12 Fri] - Started Learning javascript and practised some programs in w3schools website
** Week 2 [2017-05-15 Mon] till [2017-05-21 Sun]
   + [2017-05-15 Mon] - Started and Completed Doing assignment-1.Went deep into strings concept and in-built functions to retrive required information from strings.All the test-cases were satisfying 
   + [2017-05-16 Tues] - Started and Completed doing assignment-2.Learned array concepts completely.Test-cases satisfied
   + [2017-05-17 Wed] - Started and Completed doing assignment-3.Workedout with prakash as the concept required for this is bit confusing.Classes and methods are some confusing topics
   + [2017-05-18 Thurs]- Didn't understand assignment-4 of javascript so we moved on to python and learned python basics and some test-cases etc
   + [2017-05-19 Fri] - Absent
** Week 3 [2017-05-22 Mon] till [2017-05-28 Sun]
   + [2017-05-22 Mon] - Absent
   + [2017-05-23 Tues] - Reinstalled my machine with ubuntu as the OS crashed hard disk and hard-disk became completely empty.Clarified some doubts in python with prakash sir.
   + [2017-05-24 Wed] - Absent
   + [2017-05-25 Thurs] - Installed Emacs and learned how to write .org files and started to work on Automation of cluster.Mentored by siva sir
   + [2017-05-26 Fri] - Started learning Ansible-playbook and started Automating the initial step - Bridging
   
** Week 4 [2017-05-29 Mon] till [2017-05-31 Wed]
   + [2017-05-29 Mon] - Resolved some issues while bridging network.Completed automation of bridge network part.Pushed to github link is mentioned below.Bridge part is in basesetup in src/roles directory
   + [2017-05-30 Tues] - Automated installing openvz part but there is some trouble for installing proxy in ansible while installing git 
   + [2017-05-31 Wed] - Resolved issue of proxy by using environment module in ansible.Finally completed the openvz installation and automation of it 

* Month of June 
** Week 4 [2017-06-01 Thurs] till [2017-06-04 sun]
   + [2017-06-01 Thu]-Continuing automation of cluster,Worked on Creationof cluster components/servers automated cluster creation using ansible.Automated cluster router container configuration

   + [2017-06-02 Fri]-Fixed some bugs in network files to make router configuration successfull.Automation of Router is Successfull with internet access.Partially Automated Configuration-node-server because of a small bug popping up when running with proxy.Fixed Proxy issue which took max time of the day.Installed Openssh in Config-node container by automation
** Week 5 [2017-06-05] till [2017-06-11 sun]
  + [2017-06-05 Mon]-Automated ossec-server,rsyslog-server.Stuck on config-server while creating user in remote user.Initial configuration of dns-private-server and public-server,nagios-server,rsnapshot-server,ads-server is done.Need to configure little bit after completion of config-server
  + [2017-06-06 Tues]-Fixed user creation problem by directly running on remote user.Automated copying ssh keys of localhost to config server, Copying config-server keys to localmachine and to router.Stuck at cloning repository from bitbucket using ssh. We added .pub key on bitbucket.org in access keys section,then tried to clone repository.But we faced persistent error clonning
  + [2017-06-07 Wed]-Using Corkscrew command fixed the proxy issue while cloning the repository.Finally completed automating config-server.Configured all the containers and ensured that they are running internet and automated it completely.Fixed proxy issue of all the containers by writing a playbook that actually setsup proxy in all the containers in yum.config file.All the containers contains the ansible server ssh keys so that ansible can control or connect to all other containers.Completed configuring dns-server both public and private.Already existing playbooks that need to be executed in ansible machine are automated and working fine
  + [2017-06-08 Thu]-tangled all the up-to-date files into repository.Completed configuring ossec-server,rsyslog-server,nagios-server,reverse-proxy-server.Started working on ads-server.Copied ssh keys of host-machine to ads server after generating keys in ads-server.Replaced some files needed.Cloned setup-ovpl-centos repository.Need to create a new repository for setup-ovpl-centos.While configuring router using already created playbook there was error popping up.Need to check this issue by going through old playbooks
  + [2017-06-09 Fri]-Created new repository for cloning both during openvz step and also for cloning in ads-server.Created two branches ,master is for openvz and cluster-ads is for ads-server.Fixed router problem need to configure again for testing.Configured Some part in ads-server.Stuck at file issue after executing script.Moved forward to site.yaml step and automated it.Need to fixed script issue and complete cluster as soon as possible.
** Week 6 [2017-06-12 Mon] till [2017-06-18 Sun]
  + [2017-06-12 Mon]- Automated till site part to make site.yaml file working fine but there are some proxy issues need to be resolved.Router file is completely working fine and need to check on replace file once to make sure it works fine in all cases.Automated  router configuration.ADS needs to be done for completing the whole cluster.System-model need to be replaced/or some changes should to be make to make router configuring step work better.Iptables file changed in variable section of system-model in github or bitbucket.
  + [2017-06-13 Tues]- Fixed some bugs in site.yaml.Changed some iptables files in system-model repository.Site.yaml works fine.Need to look into ADS server to fix some changes and should automate it
* Repository link
  [[https://github.com/vlead/cluster-automation][cluster-automation repository]] 
 




