#+TITLE: Time sheet
#+AUTHOR: Utkarsh
#+DATE: [2017-06-01 Thu]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document holds the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad.

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] 
     Today the day commenced with the brief introduction of all the projects here at vlead and then
     assignment of our projects. Basic aim was to successfully set Lab Data Service on our
     development environment. In the morning session I setted up my laptop with git, emacs and mysql and then
     in the afternoon following the documentation provided in the repository LDS was setted up and run. I will
     be setting it up again in my virtual machine tonight, since some issues were reported with ubuntu version.
     Along with this Rest APIs were studied and a quick overview of app design was taken using the
     documentation provided in the build folder. 
   + [2017-06-02 Fri]
     The day commenced with the standup of my understanding of the documentation given to be read which was 
     followed by a thorough explaination of the implementation and the documentation by the mentor. Then I tried out
     Rest APIs to get data from the LDS app after going through the documentation once more. Most of the requirements
     regarding implementation of login, logout pages for the LDS were looked upon, noted and discussed. These reqirements
     included usage of sessions, login management, user role and thoughts about databases management. Then various 
     tutorials were studied for implementing OAuth securely (for logins) with in a small personalized flask app and then 
     an app that used Google Auth. and Twitter Auth. were coded and tested just to brush up the concepts learnt. A little 
     reading about schemas, security issues related to OAuth, login managers and different OAuth providers was also done.
** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon]
     A little change regarding to our approach previously was decided in the morning which then required me 
     to assess the requirements and data model for the lds system again with my mentor and my partner. The 
     morning session was utilized in this task and after this I quickly went back to the assigned issue of 
     creating an app with Google OAuth. Solving many bugs for couple of hours I had it working an hour after
     the lunch. Then time was spent optimizing the code and fixing some of its security flaws along with some 
     testing. Furthermore Design and Data Implementations of Outreach Portal was done in order to help myself 
     with the integration process that should be due for tomorrow. Thus today's issue has been done and now
     documentation is also been provided for today.
   + [2017-07-05 Tue]
     Morning session was spent improving and making the APIs working provided by my partner and thus integrating
     it to our app which already included login and logout apis with Google OAuth. Integration was completed till the 
     afternoon and then all routes were tested using httprequester. Models for app was reviewed from the latest 
     data model provided by the mentor and the APIs just implemented. Then I worked with my partner creating unit
     testcases but we had some problems regarding registering our routes for it. So, unit testing is due tomorrow
     but will tried to be worked till tonight. Further APIs error codes were updated along with some other changes. 
   + [2017-07-06 Wed]
     As decided morning session started with debugging of Unittest codes codes. We were finally able to register all
     the routes by using app's blueprint. Then test cases of all the APIs were written down (each test class has multiple
     test cases) and tested and then with then controllers were also changed accordingly thus code was made more reliable. 
     Documentation regarding testcases were also written. Then in the afternoon session work on errorhandling was looked 
     upon and then redirection were checked. 404 redirection error was finally fixed, fault was found with my jinja code.
     After this we wrote some more html files for the login and index pages. Documentation regarding all of them was
     also written down.
   + [2017-07-07 Thurs]
     Login page, Autherization, 404 pages were written from the scratch today and then bootstrap and css were also implemented 
     to them and Guest and Admin pages were also written and worked upon. Now we have a home page which has a login button in 
     order to go the google auth page and then user is check in the database. Couple of login errors were fixed and 
     JavaScripts were also written. UnitTest cases were updated. Roles were finally integrated in the controllers using sessions 
     which made me to some of the routes and furthermore sending user data to home pages was also implemented in the index home page. 
     In the afternoon final datamodel was reviewed, so I had to implement left out checks in each of the routes to make it fully 
     specify the database model followed. Documentation for APIs were updated and error codes were added. Further styling will be done
     by tomorrow.
   + [2017-06-09 Fri]  
     I worked upon HTML and more CSS, JS whole night which was inregrated today in our codes, changes were also made in to the
     documentation regarding the same. All the routes and Unitest cases were tetsed for the presentation. Multi user login at the same 
     time was tested using many browser and incognito sessions. Changes were made accordingly. Unittesting still needs some attention
     due to extra required admin auth decorator, which I would be tackling tonight. Later part of morning session went in presentation.
     Afternoon session was used to acknowledge the feedback given by other mentors regarding new APIs frameworks such as Jango and
     Swagger. Tutorials and documentation were readed and will be further explored in the weekend. Also tried a bit of angular js as 
     suggested in the feedback. Build still needs some fixing rest works fine, documentation was updated with fixed data structure in
     the evening with my partner.

* Month of July
