#+TITLE: Time sheet
#+AUTHOR: Yahnit Sirineni
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad


* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - 
In the morning , we had an introduction session where the team of VLEAD told us about their projects and then later we were assigned projects. 
We worked on setting the developent environment on our machines.
In the afternoon, I have set up Lab Data Service server(LDS) on my machine .
I had set up vagrant VM , so i had to install emacs,git and all the python dependancies again.
After the server was setup, I had gone through different API's and got a clear idea what was happening.
Also, I have gone through the documentation of all the API's which were implemented.

  + [2017-06-02 Fri] -
In the morning, we had a brief standup session for around 15 minutes where
our mentor had tested my understanding on the documentation and also 
cleared few misconceptions and doubts. Later, my mentor explained the 
LDS application in detail (Requirements,Design,Data Model etc).
Then, I have gone through the implementation of all the REST API's
along with the test cases.
Then, I and my teammate then sat and discussed about the implementation 
of login page. The requirements of login page came out to be sessions,
types of roles, user being added by the admin to be able to avail LDS 
services. We have brushed up the implementation of Google OAuth which
we have decided to use for the login page.  


** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon]
     
In the morning we have discussed about the requirements and data model of LDS. 
We made a clear idea as on how to proceed further. Also, my project manager
gave a milestone that is to be reached by friday. We have implemented 
Google authorisation and Authentication. Sign in and Sign out were working 
properly. We also started writing the backend for users. We created 2 tables
,one for users and one for roles. We have implemented routes like Add User,
Add role,Show users and show roles.

  +[2017-06-06 Tue]

In the morning I have implemented the following API routes. Delete User,Delete Role, Update User.
Then, I and my teammate sat together and integrated both our codes. He has implemented Google
Authorisation and Authentication. We have succesfully merged both our codes and all the routes
were working perfectly fine.
In the afternoon, I started documentation for all the routes Add User,Add role,Delete User,Delete Role,
Show users,Show roles,Update user and completed it.
We also started writing testcases for our code but both of us were struck and we were not able to
debug our code for test cases.

  +[2017-06-07 Wed]

In the morning we have written test cases for all the API routes which we have implemented.
For each route, we wrote atleast 3 testcases taking care of all the possible errors.
After writing the test cases , both of us integrated our codes and made sure everything
was working perfectly fine. I also implemented another API route which checks whether
a user exists in the database or not, since while logging in we have to check whether the 
user has availed to LDS or not. Then,We integrated our codes. Later we wrote HTML files
to be showed while logging in and implemented checking the user is there in database or not.
Then we wrote the documentation of all the test cases for all the API routes.
Also documentation of extra routes and html was done.  

  +[2017-06-08 Thu]

In the morning we have made changes to our login routes. After the Login page is shown,
if the user clicks the login button, we redirected him to the google Auth page and
then made a check if the user is there in the database or not.If the user is there 
we navigated him to the index page. I have written HTML code for Guest and Admin
pages and added all the links of LDS though the routes have not been linked yet.
To the Admin index page,we have added CRUD operations though we have'nt implemented
frontend for that.
I implemented roles.For performing certain operations like Add,Delete or Update
I wrote functions to check the authorisation. My teammate worked on styling.
Later we have integrated our codes. We have redirected the user to Admin page
if he is an admin or redirected him to guest page if he is a guest.
For that , we have implemented sessions. We also stored the role of the user
in the session so that we could display it on the Home page.
Documentation of Config files and init files were added.

 +[2017-06-09 Fri]

In the morning, We added the remaining html and css code to the documentation .
 Then we had project presentation for 3 hours. Later, i have gone through 
swagger which one of my mentors suggested to go through.
 I also made adjustments to the documentation making sure that everything was in the 
right place. We we made sure that make file ran without any errors. I adjuested
our code according the directory strucure . 


** Week 3 [2017-06-12 Mon] till [2017-06-18 Sun]

 +[2017-06-12 Mon]

In the morning, i have tried to implement front end for add user, add role etc.
But, I could'nt do it. There was some problem with the directory structure.
So, i had to fix the directory structure and tangling problems. Later, i have
gone through Jinja templates which we decided to use for frontend. I referred 
many tutorials in the internet and understood the actual implementation of
Jinja templates.

+[2017-06-13 Tue]

In the morning we have fixed the testcases. Testcases were done last week only
but at that point of time login and authorisation was not done.We have fixed
the test cases keeping in mind login and admin authorisation.We faced a lot 
of build errors while running make. We have fixed all the build errors 
and our app has tangles perfectly well and was working fine. Thirumal sir
has explained about the web app short course and asked us to go through it
because we will be implementing lds dashboard in a similar way.

+[2017-06-14 Wed]

Deployment has been done with whatever we have done. I have setup web-app
short course on my machine. The application did not work perfectly as we
have faced problems with the google oauth.However, i have looked at the code
and tried to understand how the API's were implemented and also understood
the implementation of frontend.Thirumal sir has taught us user directory
with hash routing in the ITWS2 course. I have downloaded that and had a look
at how the hash routing was implemented.I also browsed about single page
applications.

+[2017-06-15 Thu]

We have done the release today. I have started writing the specifications
of the JSON file which will be used to render html.I have given the
specifications for the add-user container. I and Thirumal sir
sat and discussed on how to decode the json file and we 
have decided on an alogorithm to decode the json spec file.
I then wrote a javascript function to decode the JSON and render into html.

+[2017-06-16 Fri]

We made a slight change to the function do decode the JSON file.
We had used a reccursive approach , basically its like a tree.
Then we had project presentation from 11-1.30. Later, i wrote
the JSON specifications for all the other CRUD operations also,
Add role, Edir User,Delete User,Delete Role,Show Roles and Users.
And then we had a Tech talk.





** Week 4 [2017-06-19 Mon] till [2017-06-25 Sun]

+[2017-06-19 Mon]

I started writing event handlers for the frontend of CRUD operations.
I have written the event handlers for Add user and Add role operations.
Based on a JSON object,the html is displayed.To perform the operations
i used AJAX calls and based on the response from the server side,i 
have generated specific messages.

+[2017-06-20 Tue]

We are done with login-logout. When a User is not logged in,the LOGIN
button is shown and when the user is logges in,LOGOUT button is shown.
We have integrated the handlers of Add User and Add role. While adding
a user,initially we provided a text box,but we have placed a dropdown
box so that the admin can choose from the available roles. We have
now taken our JSON spec object and generated HTML based on the JSOn file.

+[2017-06-21 Wed]

All the necessary event handlers have been written.We are now done 
with all the CRUD operations.We have created a JSON file with which 
creates necessaty form and displays.All the operations are working 
well.We were hiding and displaying things based on the
operations without any routing. We have been adviced to use hash
routing, so we started implementing hash routing.

+[2017-06-22 Thu]

We worked on integrating backend and frontend.We have linked the
event handlers with the functions.Later in the standup, we have
made some changes on the behavior of the frontend.Thirumal sir
has given a specification of how show-users,show-roles,add-user,
add-role should look.We have worked on those specifications.
We were alomost done with the front end of USER and ROLES.
Only a very few minor changes were left. Documenatation of
the frontend was also done.we have pushed the code to git. 

+[2017-06-23 Fri]

We have implemented complete frontend for the CRUD operations
of User and Roles.We have faced an issue with update and 
delete buttons. Even though we deleted the buttons, the
event handlers were not getting dettached from the buttons.
We struggled a lot on this issue. Later, Thirumal Sir
has joined us and after a long effort we could fix that issue.
we have then pushed our code into the org files and documentation
was written.


** Week 5 [2017-06-27 Tue] till [2017-07-02 Sun]

+[2017-06-27 Tue]

A part of Documentation was changed , we have written in more detail
as suggested by Thirumal Sir.For each and very piece of code we have
started wrotong description in detail. However we could do only for 
4 pieces of code.I then worked on writing frontend for the LDS dashboard.
Added some event listeners and also placed dropdowns for assets,developers,
etc which will be used while adding a lab or experiment.I have tested whether
the dropdowns were being populated properly or not.

+[2017-06-28 Wed]

On leave

+[2017-06-29 Thu]

I have worked on the json spec files of all the add operations.
The code was pushed into the org files. I faced lot of problem
while tangling the code. After a long effort i could manage to
tangle all the files. Later i faced syntax errors.The JSON file
had quite many syntax errors. Since the json spec file was as 
huge as 2500 lines,it took quite a lot of time to fix all the 
syntax errors and ensuring that proper HTML is being rendered
from the JSON spec file.


* Month of July
