#+TITLE: Time sheet
#+AUTHOR: Yahnit Sirineni
#+DATE: [2017-06-01 Fri]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document hols the time sheets for my work during the summer internship
  at VLEAD, IIIT Hyderabad

* Month of June
** Week 1 [2017-06-01 Thu] till [2017-06-04 Sun]
   + [2017-06-01 Thu] - 
In the morning , we had an introduction session where the team of VLEAD told us about their projects and then later we were assigned projects. 
We worked on setting the developent environment on our machines.
In the afternoon, I have set up Lab Data Service server(LDS) on my machine .
I had set up vagrant VM , so i had to install emacs,git and all the python dependancies again.
After the server was setup, I had gone through different API's and got a clear idea what was happening.
Also, I have gone through the documentation of all the API's which were implemented.

  + [2017-06-02 Fri] -
In the morning, we had a brief standup session for around 15 minutes where
our mentor had tested my understanding on the documentation and also 
cleared few misconceptions and doubts. Later, my mentor explained the 
LDS application in detail (Requirements,Design,Data Model etc).
Then, I have gone through the implementation of all the REST API's
along with the test cases.
Then, I and my teammate then sat and discussed about the implementation 
of login page. The requirements of login page came out to be sessions,
types of roles, user being added by the admin to be able to avail LDS 
services. We have brushed up the implementation of Google OAuth which
we have decided to use for the login page.  


** Week 2 [2017-06-05 Mon] till [2017-06-11 Sun]
   + [2017-06-05 Mon]
     
In the morning we have discussed about the requirements and data model of LDS. 
We made a clear idea as on how to proceed further. Also, my project manager
gave a milestone that is to be reached by friday. We have implemented 
Google authorisation and Authentication. Sign in and Sign out were working 
properly. We also started writing the backend for users. We created 2 tables
,one for users and one for roles. We have implemented routes like Add User,
Add role,Show users and show roles.

  +[2017-06-06 Tue]

In the morning I have implemented the following API routes. Delete User,Delete Role, Update User.
Then, I and my teammate sat together and integrated both our codes. He has implemented Google
Authorisation and Authentication. We have succesfully merged both our codes and all the routes
were working perfectly fine.
In the afternoon, I started documentation for all the routes Add User,Add role,Delete User,Delete Role,
Show users,Show roles,Update user and completed it.
We also started writing testcases for our code but both of us were struck and we were not able to
debug our code for test cases.

  +[2017-06-07 Wed]

In the morning we have written test cases for all the API routes which we have implemented.
For each route, we wrote atleast 3 testcases taking care of all the possible errors.
After writing the test cases , both of us integrated our codes and made sure everything
was working perfectly fine. I also implemented another API route which checks whether
a user exists in the database or not, since while logging in we have to check whether the 
user has availed to LDS or not. Then,We integrated our codes. Later we wrote HTML files
to be showed while logging in and implemented checking the user is there in database or not.
Then we wrote the documentation of all the test cases for all the API routes.
Also documentation of extra routes and html was done.  

  +[2017-06-08 Thu]

In the morning we have made changes to our login routes. After the Login page is shown,
if the user clicks the login button, we redirected him to the google Auth page and
then made a check if the user is there in the database or not.If the user is there 
we navigated him to the index page. I have written HTML code for Guest and Admin
pages and added all the links of LDS though the routes have not been linked yet.
To the Admin index page,we have added CRUD operations though we have'nt implemented
frontend for that.
I implemented roles.For performing certain operations like Add,Delete or Update
I wrote functions to check the authorisation. My teammate worked on styling.
Later we have integrated our codes. We have redirected the user to Admin page
if he is an admin or redirected him to guest page if he is a guest.
For that , we have implemented sessions. We also stored the role of the user
in the session so that we could display it on the Home page.
Documentation of Config files and init files were added.

 +[2017-06-09 Fri]

In the morning, We added the remaining html and css code to the documentation .
 Then we had project presentation for 3 hours. Later, i have gone through 
swagger which one of my mentors suggested to go through.
 I also made adjustments to the documentation making sure that everything was in the 
right place. We we made sure that make file ran without any errors. I adjuested
our code according the directory strucure . 

* Month of July
